apiVersion: v1
kind: Service
metadata:
  name: url-shortner-service
  # namespace: url-shortner-ns
spec:
  selector:
    app: url-shortner
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000

  
