name: CI-CD

on:
    push:
        branches: [main]

    # optional mannual trigger
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.ACCESSTOKEN }}

            - name: Build and Push Docker image
              run: |
                  docker build -t ghcr.io/${{ github.repository }}:latest .
                  docker push ghcr.io/${{ github.repository }}:latest

            - name: Deploy to Kubernetes (kind/minikube)
              run: |
                  kubectl apply -f kubernetes/
